### ISSUE TITLE
index page has overlapping content when site menus references long pages

### ISSUE THREAD

**Issue by lschierer** [adobe/hugo-spectrum#27]
### Expected Behaviour

Page displays legibly 

### Actual Behaviour

text overlaps and renders illegibly 

#### Steps to Reproduce

set up a .Site.Menus.main that references pages that have several long paragraphs of text on them.   See that the text in the pages overlap.

#### Platform and Version

```
officium:EvonyTKRTips luke$ npx hugo version
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended darwin/arm64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
officium:EvonyTKRTips luke$
```
#### Sample Code that illustrates the problem

this is entirely dependent on what the 
```
    {{ range .Site.Menus.main }}
``` 
in 
```
hugo-spectrum/layouts/index.html 
```
finds.

**Comment by OneCricketeer** [comment]
We noticed that when we include an image in one of the content pages, it'll also render in the home menu overview page...

Do you know if there is a way to add padding? Otherwise, I was thinking go with something like `{{ .Params.description }}`, but for each sub-page rather than Hugo params.
